#!/bin/bash
rm /tmp/screenshot.png
scrot /tmp/screenshot.png
convert /tmp/screenshot.png -blur 0x9 /tmp/screenshotblur.png
i3lock -i /tmp/screenshotblur.png -R 120 -F 30 -l 1F222B -o 70FF97 -w FF5144
